// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD86PGSDgYnUwoouLFEs02mrlmAz40Nvm4',
    appId: '1:155700404411:web:bc204c32370b54734f499e',
    messagingSenderId: '155700404411',
    projectId: 'notes-44b1b',
    authDomain: 'notes-44b1b.firebaseapp.com',
    storageBucket: 'notes-44b1b.firebasestorage.app',
    measurementId: 'G-98HMCBZ21J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuQCq7cwOw5_FeZTbuRJ75j6IMPJ9htAU',
    appId: '1:155700404411:android:35fbda724539577e4f499e',
    messagingSenderId: '155700404411',
    projectId: 'notes-44b1b',
    storageBucket: 'notes-44b1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiycymFTxFxoBX9xb-HI5iwyhnyGKVJFo',
    appId: '1:155700404411:ios:6aebe57adbe51f654f499e',
    messagingSenderId: '155700404411',
    projectId: 'notes-44b1b',
    storageBucket: 'notes-44b1b.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiycymFTxFxoBX9xb-HI5iwyhnyGKVJFo',
    appId: '1:155700404411:ios:6aebe57adbe51f654f499e',
    messagingSenderId: '155700404411',
    projectId: 'notes-44b1b',
    storageBucket: 'notes-44b1b.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD86PGSDgYnUwoouLFEs02mrlmAz40Nvm4',
    appId: '1:155700404411:web:90391818acd387904f499e',
    messagingSenderId: '155700404411',
    projectId: 'notes-44b1b',
    authDomain: 'notes-44b1b.firebaseapp.com',
    storageBucket: 'notes-44b1b.firebasestorage.app',
    measurementId: 'G-2X0VDE7JR7',
  );
}
